### 내장함수

In [2]:
def positive(l): 
    result = [] 
    for i in l: 
        if i > 0: 
            result.append(i) 
    return result

print(positive([1,-3,2,0,-5,6]))

[1, 2, 6]


In [3]:
#filter1.py
def positive(x):
    return x > 0

print(list(filter(positive, [1, -3, 2, 0, -5, 6])))
#filter로 부르면 리스트로 따로 안부르고 한번에 리스트값을 읽어올 수 있음

[1, 2, 6]


In [5]:
#람다는 소모적인 함수
list(filter(lambda x: x>0, [1,-3,2,0,-5,6]))

[1, 2, 6]

In [6]:
list(map(lambda a :a*2, [1,2,3,4]))
# map(f, iterable)은 함수(f)와 반복 가능한(iterable) 자료형을 입력으로 받는다. 
# map은 입력받은 자료형의 각 요소를 함수 f가 수행한 결과를 묶어서 돌려주는 함수이다.

[2, 4, 6, 8]

In [8]:
#zip은 첫번째와 두번째 인수  갯수를 맞춰야한다. 쌍을 맞추어주는것
#파라미터 조합을 만들 때
list(zip([1,2,3],[4,5,6]))

[(1, 4), (2, 5), (3, 6)]

### 외장함수

In [9]:
import sys
sys.path

['C:\\Users\\student',
 'C:\\Users\\student\\Anaconda3\\python37.zip',
 'C:\\Users\\student\\Anaconda3\\DLLs',
 'C:\\Users\\student\\Anaconda3\\lib',
 'C:\\Users\\student\\Anaconda3',
 '',
 'C:\\Users\\student\\AppData\\Roaming\\Python\\Python37\\site-packages',
 'C:\\Users\\student\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\student\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\student\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\student\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\student\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\student\\.ipython']

In [11]:
# import는 필요할 때 마다 올림
# install은 딱 한번
!pip install numpy

In [12]:
!pip install numpy

In [13]:
# path_append.py
import sys
sys.path.append("C:/doit/mymod")

In [16]:
# 파이썬 객체정보를 파일로 빼고 파일로 볼 수 있게 해주는 것  => pickle
# pickle은 객체의 형태를 그대로 유지하면서 파일에 저장하고 불러올 수 있게 하는 모듈이다

import pickle
f = open("test.txt", 'wb') #write binary
data = {1: 'python', 2: 'you need'}
pickle.dump(data, f)  #저장할 때는 dump
f.close()

In [17]:
import pickle
f = open("test.txt", 'rb')
data = pickle.load(f)  #불러오는건 load
print(data)
{2:'you need', 1:'python'}

{1: 'python', 2: 'you need'}


{2: 'you need', 1: 'python'}

In [21]:
import glob
glob.glob("c:\py_data/*")

['c:\\py_data\\Day03_리스트,튜플자료형.ipynb',
 'c:\\py_data\\Day04_함수형.ipynb',
 'c:\\py_data\\새파일.txt']

### 정규 프로그래밍

In [23]:
data = """
park 800905-1049118
kim  700905-1059119
"""

result = []
for line in data.split("\n"):
    word_result = []
    for word in line.split(" "):
        if len(word) == 14 and word[:6].isdigit() and word[7:].isdigit():
            word = word[:6] + "-" + "*******"
        word_result.append(word)
    result.append(" ".join(word_result))
print("\n".join(result))



park 800905-*******
kim  700905-*******



In [25]:
#정규표현식은 1)내가 찾고자 하는 문자열의 패턴을 지정
#2) 패턴이 일치하는 문자열에 대하여 대체, 찾기기능 적음


import re 

data = """
park 800905-1049118
kim  700905-1059119
"""

pat = re.compile("(\d{6})[-]\d{7}")
print(pat.sub("\g<1>-*******", data))


park 800905-*******
kim  700905-*******



# 데이터 분석을 위한 패키지

## 11.1 배열 데이터를 효과적으로 다루는 NumPy

### 배열 생성하기
#### 페이지 215

In [1]:
import numpy as np
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)  #nd array로 바뀌는 것 -> 벡터매트릭스처럼 바뀌는 느낌
a1

array([0, 1, 2, 3, 4, 5])

In [2]:
a1.dtype

dtype('int32')

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
b1=np.arange(12).reshape(4,3)
b1.shape
b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
num_f1=np.array([10,21,0.549,4.75,5.98])
num_i1=num_f1.astype(int)  #강제 형변환 
num_i1

array([10, 21,  0,  4,  5])

In [11]:
num_i1.dtype

dtype('int32')

In [13]:
a1 = np.array([10,20,30,40,50])
a1

array([10, 20, 30, 40, 50])

In [14]:
test=[[0,10],[20,30],[40,50]]
#test2=test.reshape(3,2)
test2=np.array(test)
test2[0,1]

10

In [16]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
a2[1]=np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 90]])

In [18]:
a2[2,1]

80

In [19]:
a2[[0,0],[2,1]]

array([30, 20])

In [21]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [22]:
a>3 #값을 리턴하는게 아니라 트루펄스만 알려줌

array([False, False, False,  True,  True,  True])

In [23]:
a[a>3] # 조건을 따르는 리스트가 생성됨

array([4, 5, 6])

In [24]:
a[(a%2)==0]

array([2, 4, 6])

#### 슬라이싱

In [25]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [26]:
#시리즈는 행이 여러개 있는 것